"""
Run this to write a clean rag_service.py directly.
Usage: docker compose exec backend python scripts/fix_rag.py
"""
import os

content = [
    "import re",
    "import torch",
    "from sentence_transformers import SentenceTransformer, util",
    "from transformers import pipeline",
    "",
    "_embedder = None",
    "_qa_pipeline = None",
    "_scope_embeddings = None",
    "DEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'",
    "",
    "LDCU_DOMAIN_ANCHORS = [",
    "    'enrollment requirements admission LdCU Liceo',",
    "    'tuition fees payment cashier finance',",
    "    'scholarship grant financial assistance application',",
    "    'transcript of records TOR registrar office',",
    "    'academic calendar semester schedule examination',",
    "    'graduation clearance diploma commencement',",
    "    'subject units curriculum course program',",
    "    'student handbook university policies procedures',",
    "    'adding dropping subjects enrollment period',",
    "    'GPA grades passing grading system',",
    "    'late enrollment fee penalty',",
    "    'transferee student admission requirements',",
    "    'Liceo de Cagayan University LdCU CDO',",
    "]",
    "SCOPE_THRESHOLD = 0.22",
    "",
    "def load_models():",
    "    global _embedder, _qa_pipeline, _scope_embeddings",
    "    print(f'Loading ML models on device: {DEVICE}')",
    "    _embedder = SentenceTransformer('all-MiniLM-L6-v2', device=DEVICE)",
    "    print('Embedding model loaded (all-MiniLM-L6-v2)')",
    "    _qa_pipeline = pipeline('question-answering', model='deepset/roberta-base-squad2', device=0 if DEVICE=='cuda' else -1)",
    "    print('QA model loaded (deepset/roberta-base-squad2)')",
    "    _scope_embeddings = _embedder.encode(LDCU_DOMAIN_ANCHORS, convert_to_tensor=True, show_progress_bar=False)",
    "    print('All systems ready. LISSA is online.')",
    "",
    "def is_in_scope(question):",
    "    q_emb = _embedder.encode(question, convert_to_tensor=True, show_progress_bar=False)",
    "    sims = util.cos_sim(q_emb, _scope_embeddings)[0].tolist()",
    "    max_sim = max(sims)",
    "    return max_sim >= SCOPE_THRESHOLD, round(max_sim, 4)",
    "",
    "def embed_texts(texts):",
    "    return _embedder.encode(texts, show_progress_bar=False).tolist()",
    "",
    "def embed_query(query):",
    "    return _embedder.encode(query, show_progress_bar=False).tolist()",
    "",
    "def rerank_chunks(question, chunks):",
    "    if not chunks:",
    "        return chunks",
    "    q_emb = _embedder.encode(question, convert_to_tensor=True)",
    "    c_emb = _embedder.encode(chunks, convert_to_tensor=True)",
    "    scores = util.cos_sim(q_emb, c_emb)[0].tolist()",
    "    ranked = sorted(zip(scores, chunks), key=lambda x: x[0], reverse=True)",
    "    return [chunk for _, chunk in ranked]",
    "",
    "def clean_text(text):",
    "    text = re.sub(r'\\(cid:\\d+\\)', ' ', text)",
    "    text = re.sub(r'^(Q:|A:)\\s*', '', text, flags=re.MULTILINE)",
    "    text = re.sub(r'\\n+', ' ', text)",
    "    text = re.sub(r'\\s{2,}', ' ', text)",
    "    return text.strip()",
    "",
    "def is_table_chunk(text):",
    "    dash_count = text.count('\u2014') + text.count('\u2013') + text.count(' - ')",
    "    date_count = len(re.findall(r'\\b(January|February|March|April|May|June|July|August|September|October|November|December)\\s+\\d{1,2}', text))",
    "    return dash_count > 3 or date_count > 2",
    "",
    "def verify_answer(answer, context):",
    "    if not answer or not context:",
    "        return False",
    "    norm_a = re.sub(r'\\s+', ' ', answer.lower().strip())",
    "    norm_c = re.sub(r'\\s+', ' ', context.lower().strip())",
    "    return norm_a in norm_c",
    "",
    "def extract_answer(question, context_chunks):",
    "    MAX_ANSWER_CHARS = 450",
    "    MIN_CONFIDENCE = 0.25",
    "    if not context_chunks:",
    "        return {'answer': '', 'confidence': 0.0, 'context': '', 'span': ''}",
    "    reranked = rerank_chunks(question, context_chunks)",
    "    best = {'answer': '', 'confidence': 0.0, 'context': '', 'span': ''}",
    "    for chunk in reranked:",
    "        cleaned = clean_text(chunk)",
    "        if len(cleaned) < 20:",
    "            continue",
    "        try:",
    "            result = _qa_pipeline(question=question, context=cleaned, max_answer_len=200)",
    "            if not verify_answer(result['answer'], cleaned):",
    "                continue",
    "            if result['score'] > best['confidence']:",
    "                best = {'answer': result['answer'], 'confidence': round(result['score'], 4), 'context': cleaned, 'span': result['answer']}",
    "        except Exception:",
    "            continue",
    "    if not best['context'] or not best['span']:",
    "        return {'answer': '', 'confidence': 0.0, 'context': '', 'span': ''}",
    "    if best['confidence'] < MIN_CONFIDENCE:",
    "        return {'answer': '', 'confidence': best['confidence'], 'context': best['context'], 'span': ''}",
    "    span = best['span'].strip().lower()",
    "    context = best['context'].strip()",
    "    if is_table_chunk(context):",
    "        best['answer'] = re.sub(r'\\(cid:\\d+\\)', '', best['span']).strip()",
    "        return best",
    "    sentences = re.split(r'(?<=[.!?])\\s+(?=[A-Z])', context)",
    "    sentences = [s.strip() for s in sentences if len(s.strip()) > 15]",
    "    matched = [i for i, s in enumerate(sentences) if span in s.lower()]",
    "    if matched:",
    "        idx = matched[0]",
    "        selected = [sentences[idx]]",
    "        if idx + 1 < len(sentences):",
    "            next_s = sentences[idx + 1]",
    "            starts_new = re.match(r'^(Q:|A:|Note:|\\u2022|-|\\d+\\.|However|Additionally)', next_s)",
    "            if not starts_new and (len(selected[0]) + len(next_s)) < MAX_ANSWER_CHARS:",
    "                selected.append(next_s)",
    "        full_answer = ' '.join(selected)",
    "    else:",
    "        span_tokens = set(span.split())",
    "        scored = sorted([(len(span_tokens & set(s.lower().split())), s) for s in sentences], reverse=True)",
    "        full_answer = scored[0][1] if scored else best['span']",
    "    if len(full_answer) > MAX_ANSWER_CHARS:",
    "        cut = full_answer[:MAX_ANSWER_CHARS].rfind('.')",
    "        full_answer = full_answer[:cut+1] if cut > 50 else full_answer[:MAX_ANSWER_CHARS]",
    "    full_answer = re.sub(r'\\(cid:\\d+\\)', '', full_answer)",
    "    full_answer = re.sub(r'^(A:|Q:)\\s*', '', full_answer).strip()",
    "    full_answer = re.sub(r'\\s{2,}', ' ', full_answer)",
    "    best['answer'] = full_answer",
    "    return best",
]

out_path = "/app/app/services/rag_service.py"
with open(out_path, "w", encoding="utf-8") as f:
    f.write("\n".join(content))

print(f"Successfully wrote {out_path}")
print(f"Lines: {len(content)}")

# Quick syntax check
import ast
with open(out_path) as f:
    src = f.read()
try:
    ast.parse(src)
    print("Syntax check PASSED — file is valid Python")
except SyntaxError as e:
    print(f"Syntax check FAILED: {e}")